#!/bin/bash
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ -d "$DIR/.git" ]; then
   echo ".git repository exists, don't want to fuck with that"
   exit 1
fi

make -C $DIR flask || (echo "make flask failed"; make -C $DIR clean; exit 1;)
git init || (echo "git init failed"; exit 1;)

